### ISSUE TITLE
how to apply against 13 ?

### ISSUE THREAD

**Issue by seandarcy** [seanbright/asterisk-opus#1]
1. Since 13 has vp6 pass-through, no need to copy format_vp8.c, correct ??
2. We still need to copy the opus codecs ??
3. The patch fails for frame.c : 

patch -p1 < ../opus/asterisk-opus-master/asterisk.patch 
patching file build_tools/menuselect-deps.in
Hunk #1 succeeded at 41 (offset -1 lines).
patching file configure.ac
Hunk #1 succeeded at 448 (offset 20 lines).
Hunk #2 succeeded at 2212 (offset 44 lines).
patching file main/frame.c
Hunk #1 FAILED at 1029.
Hunk #2 FAILED at 1111.
2 out of 2 hunks FAILED -- saving rejects to file main/frame.c.rej
patching file makeopts.in
Hunk #1 succeeded at 273 (offset 1 line).

But do we need to patch frame.c ? Is the rest of the patch required ?

**Comment by seanbright** [comment]
Opus support for Asterisk 13 has been implemented: https://github.com/seanbright/asterisk-opus/commit/de820fbc4a79cddf1dfd5a2167ea3c8c2db76b78
