### ISSUE TITLE
Transcoding while different in Frame size = Frames lost

### ISSUE THREAD

**Issue by traud** [seanbright/asterisk-opus#13]
First of all, thank you for your transcoding module for Asterisk 13. It works great with CSipSimple (Google Android) and CounterPath Bria (Apple iOS). However while testing, I got the following warning message: `translate.c:402 framein: Out of buffer space`.

This happens for example, when Asterisk transcodes from audio-codec iLBC 30 to the audio-codec Opus. `lintoopus_frameout` is called with a frame size larger than Opus is encoding/sending. After a few seconds, the above warning message is shown and the buffer is full. Therefore, frames are lost.

Actually, this happens whenever the source codec uses a longer [packetization](https://wiki.asterisk.org/wiki/display/AST/RTP+Packetization) than the default 20 milliseconds of Opus. For example:
* with iLBC, which uses 30 ms as default
* when a higher `ptime` is specified in `sip.conf`, like `allow:opus,ulaw:30`

The solution is to use a while-loop like in commit meetecho/asterisk-opus@2975dd69a67a88610350c28dd7dabbb7af07db70. However, this alone creates too big frames on the wire, for example 20 ms 40 ms 20 ms 40 ms. Since Asterisk 13.6.0 (see ~~[ASTERISK-25353](https://issues.asterisk.org/jira/browse/ASTERISK-25353)~~) the API allows to return several frames in a linked list. I submit a pull request shortly, which fixes this issue here, leverages Asterisk 13.6.0, and is backward compatible with previous Asterisk versions.

**Comment by seanbright** [comment]
I've added you as a contributor to this repository. Go ahead with whatever changes you deem necessary.

**Comment by joshelson** [comment]
@traud Your solution actually prevents the PBX from loading at all, when applied directly to Asterisk 13.6.  You never will receive the rest of the module loads when using your patch directly on Asterisk a vanilla 13.6 install, as Asterisk hangs on the codec_opus.so load.  Looking into the reason for this now, but would recommend testing before we merge those changes.

**Comment by traud** [comment]
Mhm. I am not able to reproduce that issue, yet.

Sounds like a endless while-loop. To verify, please, change `ast_debug(3` into `ast_log(LOG_NOTICE` and tell us which method/function is looping. I tried a vanilla Asterisk 13.6 on a vanilla Ubuntu 14.04 LTS and the Opus module loads just fine here. My first commit did contain an error and did show the behaviour you describe. Please, double-chek the source of `codecs/codec_opus.c` – if `ast_trans_frameout` is called with `opvt->multiplier * samples`, you do not have the latest commit. In the latest/final commit, `ast_trans_frameout` is called with `opvt->multiplier * opvt->framesize`. Please, keep us updated, so I am able to push these commits.
