### ISSUE TITLE
asterisk-11-svn 434725 with patch

### ISSUE THREAD

**Issue by Totole** [seanbright/asterisk-opus#15]
Hi,
patching the asterisk with the patch file I got following error :
'root@pbx ~src/asterisk-11-svn (svn)-[11:434725] # patch -p1 < /usr/src/asterisk-opus-asterisk-11/asterisk.patch
patching file build_tools/menuselect-deps.in
patching file channels/chan_sip.c
Hunk #1 succeeded at 7661 (offset -143 lines).
Hunk #2 succeeded at 11026 (offset -111 lines).
Hunk #3 succeeded at 11065 (offset -111 lines).
Hunk #4 succeeded at 11133 with fuzz 1 (offset -111 lines).
Hunk #5 FAILED at 12819.
Hunk #6 succeeded at 12766 (offset -82 lines).
1 out of 6 hunks FAILED -- saving rejects to file channels/chan_sip.c.rej
patching file configure.ac
Hunk #2 succeeded at 2175 (offset 27 lines).
patching file include/asterisk/format.h
patching file main/channel.c
patching file main/format.c
Hunk #6 succeeded at 1097 (offset 12 lines).
patching file main/frame.c
Hunk #1 succeeded at 1006 (offset 4 lines).
Hunk #2 succeeded at 1130 (offset 4 lines).
patching file main/rtp_engine.c
Hunk #1 succeeded at 2326 (offset 17 lines).
Hunk #2 succeeded at 2369 (offset 17 lines).
patching file makeopts.in
Hunk #1 succeeded at 264 (offset 2 lines).
patching file res/res_rtp_asterisk.c
Hunk #2 FAILED at 357.
Hunk #3 succeeded at 3281 (offset 482 lines).
Hunk #4 succeeded at 3378 (offset 482 lines).
1 out of 4 hunks FAILED -- saving rejects to file res/res_rtp_asterisk.c.rej

How can I fix this ?
Thanks for your help

**Comment by traud** [comment]
Which branch did you download? Because you use Asterisk 11, did you consider the [original patch](https://github.com/meetecho/asterisk-opus)?

**Comment by Totole** [comment]
Sorry.
I was in wrong folder. BTW, I installed on a Banana PI asterisk 13 with latest SVN and your OPUS patch !
This page was very helpful especially for Raspberry PI and Banana PI to install it :
https://wiki.asterisk.org/wiki/display/AST/Building+and+Installing+pjproject
