### ISSUE TITLE
Asterisk-13.7.0-rc2

### ISSUE THREAD

**Issue by Totole** [seanbright/asterisk-opus#16]
Hi
Digium just release asterisk-13.7.0-rc2.
This version fixed the bug of gone pjsip module. I tried your master branch with this version but the patch file did not work.
Please modify the the patchfile so it can work with 13.7.0 version.

Thanks and merry Xmas !

**Comment by seanbright** [comment]
The 13.3 branch applies cleanly to the latest Asterisk 13 source.
