### ISSUE TITLE
OPUS only negotiates in one direction on PJSIP

### ISSUE THREAD

**Issue by shadowym** [seanbright/asterisk-opus#17]
Possible it's something odd with my setup.   Would be curious if others can reproduce.

I have my SIP softphone with OPUS as top priority codec followed by ulaw.  On the Asterisk side it's configured with the same priority on all extensions `allow=opus,ulaw`.

Asterisk v13.7.0
PJSIP v2.4.5
PhonerLite v2.34 SIP softphone
seanbright asterisk-opus from v13.3 branch

If I dial another extension it negotiates oubound as OPUS and inbound as ulaw on my SIP softphone.  If I disable all codecs on the SIP softphone except OPUS then it negotiates OPUS in both directions.

This is different than what happens if I use chan_sip.  It has the expected behaviour of negotiating OPUS in both directions.  Even if I set ulaw as the top priority codec on the asterisk side.  So it follows whatever the codec priority is on the sip softphone side in both directions which is what is supposed to happen.

**Comment by traud** [comment]
If possible, please, [provide a trace](https://wiki.asterisk.org/wiki/display/AST/Collecting+Debug+Information) of the SIP/SDP answer from Asterisk.

**Comment by traud** [comment]
Do you still face that issue, even in Asterisk 13.12 with opus_codec module from Digium?

**Comment by traud** [comment]
Please, [continue there…](//issues.asterisk.org/jira/browse/ASTERISK-26423)
If that does not fix your issue either, please, re-open this report here and attach the SIP/SDP offer and answer.
