### ISSUE TITLE
music on hold support?

### ISSUE THREAD

**Issue by chadxz** [seanbright/asterisk-opus#18]
Does anyone know whether this patch supports playback of music on hold?

I set everything up and connected an endpoint that was a WebRTC session on the other side using this simple dialplan:

```
[general]

[respoke]
exten => musicbot,1,Answer()
 same => n,Set(remoteEndpointId=${CHANNEL(remote)})
 same => n,NoOp(${remoteEndpointId})
 same => n,MusicOnHold()
```

However, when I got a log message indicating that it was starting to play the music on hold back to the endpoint, Asterisk seems to have crashed.

```
    -- Executing [musicbot@respoke:2] Set("RESPOKE/anonymous-00000000", "remoteEndpointId=urzassu") in new stack
 
    -- Executing [musicbot@respoke:3] NoOp("RESPOKE/anonymous-00000000", "urzassu") in new stack
 
    -- Executing [musicbot@respoke:4] MusicOnHold("RESPOKE/anonymous-00000000", "") in new stack
 
    -- Started music on hold, class 'default', on channel 'RESPOKE/anonymous-00000000'
 
production-chan-respoke-test-i-9e0d6117*CLI>
Disconnected from Asterisk server
Asterisk cleanly ending (0).
Executing last minute cleanups
root@production-chan-respoke-test-i-9e0d6117:/#
cmcelligott@production-chan-respoke-test-i-9e0d6117:~$
```

I haven't really dug in deep to the issue, I was just wondering whether this type of scenario *should* work with this patch.

Thanks :)

**Comment by traud** [comment]
Never tested MOH myself, but to answer your question: Yes, this should do. Therefore, if you are able to [add more details](https://wiki.asterisk.org/wiki/display/AST/Collecting+Debug+Information), this would be very welcome.

**Comment by chadxz** [comment]
@traud thanks for the response. I'll try to gather more debugging information when I have a chance, but it may take me a while.

**Comment by powerpbx** [comment]
You can try convert to sln16.  It is still transcoding but processing is mimimal and quality is twice as good as 8khz.  

     sox music_orig.wav -t raw -b 16 -r 16000 -c 1 audiofile.sln16

**Comment by chadxz** [comment]
@powerpbx I installed sln16 sound files during my asterisk compile/install using:

```
menuselect/menuselect --enable CORE-SOUNDS-EN-SLN16 menuselect.makeopts
menuselect/menuselect --enable MOH-OPSOUND-SLN16 menuselect.makeopts
menuselect/menuselect --enable EXTRA-SOUNDS-EN-SLN16 menuselect.makeopts
```

Given that, I wouldn't actually need to convert the music on hold files to sln16 right?

Here's my full Dockerfile and supporting scripts for building up the image:
https://github.com/chadxz/chan_respoke-musicbot-example/tree/opus

**Comment by powerpbx** [comment]
Yes the MOH-OPSOUNDS-SLN16 are already done for you.  I usually install all the sounds and MOH files for all the codecs I plan to use.  I think Asterisk will try to use the format requiring the least amount of transcoding.  So for example if you are using g729 it will try use the g729 sound files when ever possible.  That can have a big effect on CPU load depending on your call volume.

For OPUS I think SLN16 is the least amount of transcoding while maintaining the highest quality.

**Comment by chadxz** [comment]
Asterisk 14.0.1 has native support for opus
