### ISSUE TITLE
asterisk 13

### ISSUE THREAD

**Issue by celevra** [seanbright/asterisk-opus#2]
thank you for this nice patch, helped me a lot of times, but now we want to use asterisk 13.
do you have the time to get the patch working again?
i get these failures
Hunk #1 FAILED at 1029.
Hunk #2 FAILED at 1111.
2 out of 2 hunks FAILED -- saving rejects to file main/frame.c.rej

regards

**Comment by 0ryn** [comment]
Looks like the formating of codecs is changed. 
ast_format_set is nolonger available
dst_format and src_format are nolonger available

**Comment by Jaykah** [comment]
Same issue. Is this branch still maintained, or should we fork it for 13, since Asterisk 12 is not LTS and is bug-fix-only at this point?

**Comment by seanbright** [comment]
Feel free to fork, I don't have the time currently to fix this for 13.

**Comment by goseeped** [comment]
Oh i have same problem Vp8 passthrough on webrtc ..is not working  actually media is going to the client but when Web Browser try to decode it raise and ERROR. the curious thing is that when you use a softphone like linphone VP8 is working fine seems like format used by asterisk doesn't liked ! same clients with patched asterisk 11 or 12 all work.

**Comment by seanbright** [comment]
Opus support for Asterisk 13 has been implemented:

https://github.com/seanbright/asterisk-opus/commit/de820fbc4a79cddf1dfd5a2167ea3c8c2db76b78

**Comment by seanbright** [comment]
@goseeped vp8 passthrough should be implemented directly in Asterisk 12+.  If you are having an issue related specifically to this repository, please open a new issue and clearly explain the problem (including affected versions).

**Comment by goseeped** [comment]
@seanbright Thanks for the new patch i will tested , this should work for both channels ? i mean for chan_pjsip and chan_sip ? or it is only for chan_sip ? Thanks

**Comment by seanbright** [comment]
I don't see why it wouldn't work with {{chan_pjsip}}, but it definitely works with {{chan_sip}}.  If you have problems with {{chan_pjsip}} open a new issue and describe the problem and I will take a look.
