### ISSUE TITLE
Question: Asterisk 12 SVN

### ISSUE THREAD

**Issue by Jaykah** [seanbright/asterisk-opus#3]
Hi Sean,

Thank you for your work on the patch!

Is it still available via the svn checkout of Asterisk 12 (as in Asterisk 12.7.1 for instance)?

I looked there, but could not find any code related to transcoding.

**Comment by seanbright** [comment]
I don't follow your question.  The asterisk-12 branch has the code for Asterisk 12.

**Comment by seanbright** [comment]
Re-open if you are still having a problem.
