### ISSUE TITLE
Make not working

### ISSUE THREAD

**Issue by Jaykah** [seanbright/asterisk-opus#6]
Hi,

I am getting the following message after I apply the patch and get to "make":

```
res_format_attr_opus.c:60:25: error: redefinition of 'default_opus_attr'
 static struct opus_attr default_opus_attr = {
                         ^
res_format_attr_opus.c:54:25: note: previous definition of 'default_opus_attr' was here
 static struct opus_attr default_opus_attr = {
                         ^
res_format_attr_opus.c: In function 'opus_clone':
res_format_attr_opus.c:88:9: error: 'cloned' undeclared (first use in this function)
  return cloned;
         ^
res_format_attr_opus.c:88:9: note: each undeclared identifier is reported only once for each function it appears in
res_format_attr_opus.c: At top level:
res_format_attr_opus.c:54:25: warning: 'default_opus_attr' defined but not used [-Wunused-variable]
 static struct opus_attr default_opus_attr = {
                         ^
res_format_attr_opus.c: In function 'opus_clone':
res_format_attr_opus.c:89:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
```

I using master branch, and have tried both latest 13.2 and Asterisk SVN r431089

**Comment by shadowym** [comment]
Worked fine for me today.  Using 13.2.0 for tar.gz download.

**Comment by valter12** [comment]
Hi, I have tried with 13.2.0. Same error:
[CC] res_format_attr_opus.c -> res_format_attr_opus.o
res_format_attr_opus.c:60:25: error: redefinition of ‘default_opus_attr’
 static struct opus_attr default_opus_attr = {
                         ^
res_format_attr_opus.c:54:25: note: previous definition of ‘default_opus_attr’ was here
 static struct opus_attr default_opus_attr = {
                         ^
res_format_attr_opus.c: In function ‘opus_clone’:
res_format_attr_opus.c:88:9: error: ‘cloned’ undeclared (first use in this function)
  return cloned;
         ^
res_format_attr_opus.c:88:9: note: each undeclared identifier is reported only once for each function it appears in
res_format_attr_opus.c: At top level:
res_format_attr_opus.c:54:25: warning: ‘default_opus_attr’ defined but not used [-Wunused-variable]
 static struct opus_attr default_opus_attr = {
                         ^
res_format_attr_opus.c: In function ‘opus_clone’:
res_format_attr_opus.c:89:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [res_format_attr_opus.o] Error 1
make: *** [res] Error 2

**Comment by seanbright** [comment]
There are three branches in this repository for Asterisk 13.  One is for Asterisk 13.0 (asterisk-13.0), one is for Asterisk 13.1 (asterisk-13.1), and one is for Asterisk 13.2 (asterisk-13.2).

You need to make sure you are using the appropriate branch for your version of Asterisk.  Based on your errors, you are using asterisk.patch from either the asterisk-13.0 or asterisk-13.1 branches.

Re-open if you continue having problems after using the correct branch.

**Comment by valter12** [comment]
I have tried some of the latest versions from http://downloads.asterisk.org/pub/telephony/asterisk/old-releases/ and no luck. Following the instructions from https://github.com/seanbright/asterisk-opus/tree/asterisk-13.0 also doesn't work for me (same error as reported above). If you would provide a link to the correct branch that would save me a ton of time. Thanks!

**Comment by seanbright** [comment]
What version of Asterisk specifically are you trying to work with?

**Comment by shadowym** [comment]
If you are using Asterisk v12 for example then install asterisk-opus as follows

git clone -b asterisk-12 https://github.com/seanbright/asterisk-opus.git
