### ISSUE TITLE
Patch breaks with Asterisk 13.3.2

### ISSUE THREAD

**Issue by greenfieldtech-nirs** [seanbright/asterisk-opus#7]
When applying the patch with vanilla Asterisk version 13.3.2, you get 2 rejections:

patch -p1 < ../asterisk.patch 
patching file main/Makefile
Hunk #1 FAILED at 40.
Hunk #2 FAILED at 159.
2 out of 2 hunks FAILED -- saving rejects to file main/Makefile.rej

**Comment by seanbright** [comment]
Fixed by d15dcaea3ca4c764bf608caf3bac44eab84e2c50
