### ISSUE TITLE
USE_FEC=1 Breaks Asterisk 13.3.2

### ISSUE THREAD

**Issue by greenfieldtech-nirs** [seanbright/asterisk-opus#9]
Hi Sean,

  When enabling FEC in codec_opus.c, the result is that Asterisk is unable the create decoders/encoders above 8000. I've managed to track down the issue, with basically the 
opus_decode function passed pvt->fec as 1, however, when it gets into libopus, it is translated
into a large number - possibly a memory pointer.

  Upon starting Asterisk, we get the following all over the screen:

 Loading codec_opus.so.
  == Registered translator 'opustolin' from codec opus to slin, table cost, 960000, computational cost 1
  == Registered translator 'lintoopus' from codec slin to opus, table cost, 825000, computational cost 1999
[Jun  1 07:16:00] ERROR[12177]: codec_opus.c:245 opustolin_framein: Error decoding the Opus frame: invalid argument
[Jun  1 07:16:00] WARNING[12177]: translate.c:411 framein: opustolin12 did not update samples 0
[Jun  1 07:16:00] ERROR[12177]: codec_opus.c:245 opustolin_framein: Error decoding the Opus frame: invalid argument
[Jun  1 07:16:00] WARNING[12177]: translate.c:411 framein: opustolin12 did not update samples 0
[Jun  1 07:16:00] ERROR[12177]: codec_opus.c:245 opustolin_framein: Error decoding the Opus frame: invalid argument
[Jun  1 07:16:00] WARNING[12177]: translate.c:411 framein: opustolin12 did not update samples 0
[Jun  1 07:16:00] ERROR[12177]: codec_opus.c:245 opustolin_framein: Error decoding the Opus frame: invalid argument
[Jun  1 07:16:00] WARNING[12177]: translate.c:411 framein: opustolin12 did not update samples 0
[Jun  1 07:16:00] ERROR[12177]: codec_opus.c:245 opustolin_framein: Error decoding the Opus frame: invalid argument
[Jun  1 07:16:00] WARNING[12177]: translate.c:411 framein: opustolin12 did not update samples 0
[Jun  1 07:16:00] ERROR[12177]: codec_opus.c:245 opustolin_framein: Error decoding the Opus frame: invalid argument
[Jun  1 07:16:00] WARNING[12177]: translate.c:411 framein: opustolin12 did not update samples 0

  Any thoughts ?

Nir

**Comment by seanbright** [comment]
That code path is fairly straight forward, are you sure that the invalid argument refers to the `fec` value and not one of the other arguments?

**Comment by greenfieldtech-nirs** [comment]
Yupp,

  I've inserted printf lines to both codec_opus.c and opus_decoder.c (inside libopus) to see what is received. While the codec_opus shows pvt->fec as 1, libopus see a huge number - looks like a memory pointer.

  Initially, I thought: "looks like an .h file issue or a function header issue", but that wasn't the case. As if USE_FEC=0, libopus does receive a 0 - if it would have been an .h file issue, the error would have been consistent.

**Comment by greenfieldtech-nirs** [comment]
Ok, I believe I've found the cause for this. Asterisk is sending the frame_size for the encoder as 8000, however, when using FEC, the frame size required by Opus needs to be different. Well, to be more exact, when doing Opus to slin8000 everything is ok, however, when you start playing around with the sample rate, to allow HD native bridging, it breaks completely.

Technically speaking, we need to add FEC handling to the load_module and unload_module functions, to load the proper translation paths.

**Comment by greenfieldtech-nirs** [comment]
Ok, update: 

It would appear the issue is somewhere with how to the translators are defined. As defined in codec_opus.c:

```c
#define	BUFFER_SAMPLES	8000
#define	OPUS_SAMPLES	160
```

Now, the issue is that when using a sample size of 8000 and enabling FEC, you will fail the FEC test, as FEC requires a different sample size - depending on the rate. For example, according to the specification, for a sample rate of 48KHz, the frame size should be 120, 240, 480, 960 and a few more others. So, as a test, I've changed the BUFFER_SAMPLES to 2880, as defined by the opus 48KHz sampling - compiler, and indeed, Asterisk won't crash.

When a call went into Asterisk, I got crystal clear audio - however, when I tried performing a bridge (Either via ConfBridge softmix, via Native Bridging) - no audio was transmitted across the wire.

My assumption here is that once the sample rate differs from the default 8000 that Asterisk uses, we'll run into an issue with the various Asterisk mixers - which are most probably geared towards that sample rate. 

Again, just my assumption... What do you think?

**Comment by seanbright** [comment]
I don't have the time to really research this right now, but I would gladly merge a pull request that resolved this.

**Comment by traud** [comment]
Nir, here this repository only sees bug fixes (see the starting page of this repository why). I included a change in my fork, which should add support for Opus FEC. It requires at least Asterisk 13.7, because the state of FEC is negotiated via SIP/SDP as well. Please, [have a look…](//github.com/traud/asterisk-opus)

If your issue was not solved or you find a new issue, please, create a new issue report in my repository.
